version: "3.9"

services:
  web:
    build: .
    command: gunicorn manga_sales.main:main --bind 0.0.0.0:8080 --worker-class aiohttp.GunicornWebWorker --reload
    working_dir: /aiohttp
    volumes:
      - .:/aiohttp
    expose:
      - 8080
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:14
    env_file:
      - postgres.env 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    ports:
      - 8080:8080
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - .:/aiohttp
volumes:
  postgres_data: