version: '3'
services:
  backend:
    build: ./src/backend
    command: gunicorn config.main:main --bind 0.0.0.0:8080 --worker-class aiohttp.GunicornWebWorker --timeout 1800 --reload
    working_dir: /aiohttp/src/backend
    volumes:
      - .:/aiohttp
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14
    working_dir: /aiohttp/src/backend/.
    env_file:
      - ./src/backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  postgres_data:
