"""change scale numeric

Revision ID: 3a020a07a251
Revises: f596a7ec028b
Create Date: 2022-09-29 09:24:09.618745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a020a07a251'
down_revision = 'f596a7ec028b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
