"""add sources

Revision ID: 012f865f7f9b
Revises: bf7301e16d44
Create Date: 2022-10-05 14:16:08.611895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012f865f7f9b'
down_revision = 'bf7301e16d44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'source_id', name='_source_sourcetype_const')
    )
    op.add_column('week', sa.Column('source_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('week_date_key', 'week', type_='unique')
    op.create_unique_constraint('_source_week_const', 'week', ['date', 'source_type_id'])
    op.create_foreign_key(None, 'week', 'source_type', ['source_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'week', type_='foreignkey')
    op.drop_constraint('_source_week_const', 'week', type_='unique')
    op.create_unique_constraint('week_date_key', 'week', ['date'])
    op.drop_column('week', 'source_type_id')
    op.drop_table('source_type')
    op.drop_table('source')
    # ### end Alembic commands ###
