"""fix relationship 2

Revision ID: b335c97353b6
Revises: 76d9641ae5f8
Create Date: 2022-09-14 12:59:17.487874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b335c97353b6'
down_revision = '76d9641ae5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('week_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('title_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'title', ['title_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item', 'week', ['week_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('title_item_id_fkey', 'title', type_='foreignkey')
    op.drop_column('title', 'item_id')
    op.drop_constraint('week_item_id_fkey', 'week', type_='foreignkey')
    op.drop_column('week', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('week_item_id_fkey', 'week', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    op.add_column('title', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('title_item_id_fkey', 'title', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'title_id')
    op.drop_column('item', 'week_id')
    # ### end Alembic commands ###
