# Dockerfile
# Pull the base image
FROM node:latest
# Set the working directory
WORKDIR /react-docker
# Copy app dependencies to container
COPY ./package*.json .
# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# Install dependencies
RUN npm install
COPY . .

 