# Dockerfile
# Pull the base image
FROM node:latest as build
# Set the working directory
WORKDIR /react-docker
# Copy app dependencies to container
COPY ./package*.json ./
# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# Install dependencies
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /react-docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /react-docker/build /usr/share/nginx/html
EXPOSE 3000
