"""fix m2m

Revision ID: 636f96d15c8f
Revises: 619a49584347
Create Date: 2022-09-13 09:45:10.298324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "636f96d15c8f"
down_revision = "619a49584347"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("item_publisher_id_fkey", "item", type_="foreignkey")
    op.drop_constraint("item_author_id_fkey", "item", type_="foreignkey")
    op.drop_column("item", "publisher_id")
    op.drop_column("item", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item", sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "item",
        sa.Column("publisher_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "item_author_id_fkey", "item", "author", ["author_id"], ["id"]
    )
    op.create_foreign_key(
        "item_publisher_id_fkey", "item", "publisher", ["publisher_id"], ["id"]
    )
    # ### end Alembic commands ###
