"""empty message

Revision ID: 673f031a3cdc
Revises: a7fa2479191c
Create Date: 2023-01-21 08:22:42.675070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673f031a3cdc'
down_revision = 'a7fa2479191c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('name', sa.String(length=256), nullable=True))
    op.alter_column('link', 'link',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'link',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_column('link', 'name')
    # ### end Alembic commands ###
