"""add previous rank

Revision ID: 681d0bcd8ce0
Revises: 012f865f7f9b
Create Date: 2022-10-16 21:17:15.945578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from manga_sales.db.models import PreviousRank


# revision identifiers, used by Alembic.
revision = "681d0bcd8ce0"
down_revision = "012f865f7f9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    prev_rank = postgresql.ENUM(PreviousRank, name="previous_rank")
    prev_rank.create(op.get_bind(), checkfirst=True)
    op.add_column("item", sa.Column("previous_rank", prev_rank, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    prev_rank = postgresql.ENUM(PreviousRank, name="previous_rank")
    prev_rank.drop(op.get_bind())
    op.drop_column("item", "previous_rank")
    # ### end Alembic commands ###
