"""set sold nullable to true

Revision ID: 7259438a38f5
Revises: 681d0bcd8ce0
Create Date: 2022-10-18 15:20:55.221679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7259438a38f5"
down_revision = "681d0bcd8ce0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("item", "sold", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("item", "sold", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
