"""empty message

Revision ID: 8827759287f7
Revises: 673f031a3cdc
Create Date: 2023-01-21 08:23:43.513612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8827759287f7"
down_revision = "673f031a3cdc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("link", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "link",
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
