"""empty message

Revision ID: a7fa2479191c
Revises: d0e199c9cb8c
Create Date: 2023-01-20 19:43:17.234731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fa2479191c'
down_revision = 'd0e199c9cb8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link', 'source', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_column('link', 'source_id')
    # ### end Alembic commands ###
