"""change scale numeric

Revision ID: bf7301e16d44
Revises: 3a020a07a251
Create Date: 2022-09-29 10:03:44.352472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf7301e16d44"
down_revision = "3a020a07a251"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
