"""empty message

Revision ID: d0e199c9cb8c
Revises: 7259438a38f5
Create Date: 2023-01-20 18:08:57.783230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0e199c9cb8c"
down_revision = "7259438a38f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("source", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "description")
    op.drop_table("link")
    # ### end Alembic commands ###
