"""add cascade delete for models

Revision ID: db74e920ea75
Revises: 8827759287f7
Create Date: 2023-03-05 17:17:45.558658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db74e920ea75'
down_revision = '8827759287f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_item_author_item_id_fkey', 'association_item_author', type_='foreignkey')
    op.drop_constraint('association_item_author_author_id_fkey', 'association_item_author', type_='foreignkey')
    op.create_foreign_key(None, 'association_item_author', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_item_author', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('association_item_publisher_publisher_id_fkey', 'association_item_publisher', type_='foreignkey')
    op.drop_constraint('association_item_publisher_item_id_fkey', 'association_item_publisher', type_='foreignkey')
    op.create_foreign_key(None, 'association_item_publisher', 'publisher', ['publisher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association_item_publisher', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_item_publisher', type_='foreignkey')
    op.drop_constraint(None, 'association_item_publisher', type_='foreignkey')
    op.create_foreign_key('association_item_publisher_item_id_fkey', 'association_item_publisher', 'item', ['item_id'], ['id'])
    op.create_foreign_key('association_item_publisher_publisher_id_fkey', 'association_item_publisher', 'publisher', ['publisher_id'], ['id'])
    op.drop_constraint(None, 'association_item_author', type_='foreignkey')
    op.drop_constraint(None, 'association_item_author', type_='foreignkey')
    op.create_foreign_key('association_item_author_author_id_fkey', 'association_item_author', 'author', ['author_id'], ['id'])
    op.create_foreign_key('association_item_author_item_id_fkey', 'association_item_author', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###
