"""fix relationship

Revision ID: e25b35390327
Revises: 636f96d15c8f
Create Date: 2022-09-13 10:29:26.531953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e25b35390327"
down_revision = "636f96d15c8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("item_title_id_fkey", "item", type_="foreignkey")
    op.drop_constraint("item_week_id_fkey", "item", type_="foreignkey")
    op.drop_column("item", "title_id")
    op.drop_column("item", "week_id")
    op.add_column("title", sa.Column("item_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "title", "item", ["item_id"], ["id"])
    op.add_column("week", sa.Column("item_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "week", "item", ["item_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "week", type_="foreignkey")
    op.drop_column("week", "item_id")
    op.drop_constraint(None, "title", type_="foreignkey")
    op.drop_column("title", "item_id")
    op.add_column(
        "item", sa.Column("week_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "item", sa.Column("title_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("item_week_id_fkey", "item", "week", ["week_id"], ["id"])
    op.create_foreign_key("item_title_id_fkey", "item", "title", ["title_id"], ["id"])
    # ### end Alembic commands ###
